prefix: test
trees: 
  - taxa: 128
    iters: 30
models:
  - rate-parameters:
      dispersion:
        type: Static
        value: 1.0
      extinction:
        type: Static
        value: 1.0
    clado-parameters:
      type: Static
      allopatry: 1.0
      sympatry: 1.0
      copy: 1.0
      jump: 0.0
    ranges: 5
    iters: 10
programs:
  - name: lagrange
    binary: /home/computations/wrk/hits/lagrange-ng/bin/lagrange-ng
    profile: False
    type: lagrange-ng
    options:
      workers: 2
  - name: bigrig
    binary: /home/computations/wrk/hits/bigrig/bin/bigrig
    profile: False
    type: bigrig
