prefix: test
trees: 
  - taxa: 65536
    iters: 10
  - taxa: 32768
    iters: 10
  - taxa: 16384
    iters: 10
  - taxa: 8192
    iters: 10
  - taxa: 4096
    iters: 10
  - taxa: 2048
    iters: 10
  - taxa: 1024
    iters: 10
  - taxa: 512
    iters: 10
  - taxa: 256
    iters: 10
  - taxa: 128
    iters: 10
  - taxa: 128
    iters: 10
  - taxa: 64
    iters: 10
  - taxa: 32
    iters: 10
  - taxa: 16
    iters: 10
  - taxa: 8
    iters: 10
models:
  - rate-parameters:
      dispersion:
        type: Static
        value: 1.0
      extinction:
        type: Static
        value: 1.0
    clado-parameters:
      type: Static
      allopatry: 1.0
      sympatry: 1.0
      copy: 1.0
      jump: 0.0
    ranges: 5
    iters: 10
programs:
  - name: lagrange
    binary: /home/computations/wrk/hits/lagrange-ng/bin/lagrange-ng
    profile: False
    type: lagrange-ng
    options:
      workers: 2
  - name: bigrig
    binary: /home/computations/wrk/hits/bigrig/bin/bigrig
    profile: False
    type: bigrig
