[workspace]
authors = ["Ben Bettisworth <bwbettisworth@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "bigrig-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install = { cmd = ["R", "-f", "utils/install-biogeobears.r"] }

[dependencies]
snakemake = ">=9.14.3,<10"
r = ">=4.5,<4.6"
git = ">=2.52.0,<3"
make = ">=4.4.1,<5"
zlib = ">=1.3.1,<2"
libxml2-devel = ">=2.15.1,<3"
nlopt = ">=2.10.0,<3"
libgit2 = ">=1.9.2,<2"
libuv = ">=1.51.0,<2"
libcurl = ">=8.17.0,<9"
openssl = ">=3.6.0,<4"
ete3 = ">=3.1.3,<4"
